server:
  port: 8080
spring:
  #==========================
  # DATABASE
  #==========================
  datasource:
    url: jdbc:mysql://localhost:3306/shop_apple?useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11062003cong
    #=========================
    # JPA/HIBERNATE
    #=========================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MYSQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  message:
    basename: i18n/messages
    encoding: UTF-8
    default-lacale: en
  mvc:
    view:
      perfix: /views/
      suffix: .jsp
#=========================
# JWT
#=========================
jwt:
  expiration: 2592000 #30 day = 30 * 24 * 60 *60
  secretKey: Ys1fTeUtFNZovUTaw/mcOOyxE4yxJdcmo68G5MEGRJs=
